# Azure Pipelines configuration for Python CI
# This pipeline runs tests on multiple Python versions

trigger:
  branches:
    include:
    - main
    - develop

pr:
  branches:
    include:
    - main
    - develop

jobs:
- job: Test
  displayName: 'Run Python Tests'
  pool:
    vmImage: 'ubuntu-latest'
  
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
  
  steps:
  - task: UsePythonVersion@0
    displayName: 'Set up Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  
  - script: |
      pytest test_calculator.py -v --cov=calculator --cov-report=term-missing
    displayName: 'Run tests with pytest'
  
  - script: |
      pytest test_calculator.py --cov=calculator --cov-report=xml
    displayName: 'Generate coverage report'
  
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish coverage results'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.xml'
      failIfCoverageEmpty: false
